language: node_js
node_js:
- '6'
env:
  global:
    secure: WDLYiLwdW0Z/YNf61tyLldv9i/SmSFYcUrbtbA4IA0HmkQD+ALFth6cL66rnc4jRaCxSaIGt9TzRwoEECz8HobI7WNJleSjIxuwXnL9PSZWcSYeR4S3zKUnR74VgW/SIATGUI6mPqNX2SbIjJXpHdi5gn+l/JLovT6/i2XP932Qt6LGS+4lIsoFPyO6WBwNpHFJuu0bgiXc7McYcDihFgHi1gPXh5MuoiY+/PyWo90tGja12K3ChkQENi6WKsNVuqtetDBfzeD10eYCQ9KGskNlefd8w5sSW2m0IQERXWeRO6L1lvTLK8J+E0CrkVIOUnE6ZZu1ZqHCF2cED2PAkViE2g/khDmmJIqaPihMKJ/ZK53Qbbz7RLsqDYQHfTrFbnLMsj5heRmU/D+GsfxOCxFsMH5f2H9ZqSF+mDPtIPi3/B+lR2i+NDqcMzK6oOlNZjGaloe3B5zN2Xlqxx5nTwVMD564ERRyweP5SCSiK84dRUwSn3l7/bVBl48cVW07xHsz4S1CFCn8y9tI62TFSpoYeDFGzkchHInFQTLCsLYpuxITKdLlf46ayNKLA6z2EnCkAxlWtxpH1FwvNKLGF1JDSHnTJNpnxjClKZnHfOz8NrhLnQ+6auIgn5kfdlHAV0DDZu5RCjjZFVVANf/NAJuaHqVQH2aDcj7Dx3glD7EQ=
